# Puerto donde correrá nuestro BFF
server.port=8080
spring.application.name=bff

# URLs de nuestros microservicios internos
# Microservicio de Autenticación
microservices.auth.url=http://localhost:5001

# Microservicio de Inventario
microservices.inventory.url=http://localhost:5000

# (Opcional) Clave secreta para JWT si el BFF va a validar los tokens antes de enviarlos (API Gateway pattern)
jwt.secret.key=956b86d50cee0b1bd440f15afb780ab337c40948b3bea80777810e8365f04128
